import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const interfaceSource = readFileSync(new URL('./index.tsx', import.meta.url), 'utf8')
const oceanSource = readFileSync(new URL('./-research-ocean.tsx', import.meta.url), 'utf8')
const interfaceStyles = readFileSync(new URL('../styles.css', import.meta.url), 'utf8')
const rootSource = readFileSync(new URL('./__root.tsx', import.meta.url), 'utf8')
const faviconSource = readFileSync(new URL('../../public/favicon.svg', import.meta.url), 'utf8')

describe('interface copy contract', () => {
  it('keeps eyebrow labels and uppercase transformations out of the product', () => {
    expect(`${interfaceSource}\n${interfaceStyles}`.toLowerCase()).not.toContain('eyebrow')
    expect(interfaceStyles).not.toMatch(/text-transform\s*:\s*uppercase/i)
  })

  it('exposes fleet size without exposing internal execution profiles', () => {
    expect(interfaceSource).toContain("profile: 'live'")
    expect(interfaceSource).toContain('Number of agents')
    expect(interfaceSource).not.toContain('Execution profile')
    expect(interfaceSource).not.toContain('Live workers')
  })

  it('provides an accessible persisted theme toggle', () => {
    expect(interfaceSource).toContain("window.localStorage.getItem('fleet-theme')")
    expect(interfaceSource).toContain("window.localStorage.setItem('fleet-theme', nextTheme)")
    expect(interfaceSource).toContain("aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}")
    expect(interfaceSource).toContain('<Sun aria-hidden="true"')
    expect(interfaceSource).toContain('<Moon aria-hidden="true"')
  })

  it('renders the Fleet identity as three overlapping decorative boats', () => {
    expect(interfaceSource).toContain('<FleetBoatMark />')
    expect(interfaceSource).toContain('className="boat boat-back"')
    expect(interfaceSource).toContain('className="boat boat-middle"')
    expect(interfaceSource).toContain('className="boat boat-front"')
    expect(interfaceSource).toContain('className="fleet-boat-mark"')
    expect(interfaceSource).toContain('aria-hidden="true"')
  })

  it('uses the three-boat Fleet mark as the browser favicon', () => {
    expect(rootSource).toContain("href: '/favicon.svg'")
    expect(rootSource).toContain("sizes: 'any'")
    expect(faviconSource.match(/class="boat boat-/g)).toHaveLength(3)
    expect(faviconSource).toContain('class="boat boat-front"')
  })

  it('keeps explicitly sized interface text at a readable minimum', () => {
    const pixelFontSizes = [...interfaceStyles.matchAll(/font-size:\s*(\d+)px/g)]
      .map((match) => Number(match[1]))

    expect(pixelFontSizes.length).toBeGreaterThan(0)
    expect(Math.min(...pixelFontSizes)).toBeGreaterThanOrEqual(12)
  })

  it('keeps fleet overview and agent traces on separate full-modal screens', () => {
    expect(interfaceSource).toContain('<ResearchActivity snapshot={snapshot} onOpenAgent={openAgent} />')
    expect(interfaceSource).toContain('<h2 id="fleet-dialog-title">Fleet</h2>')
    expect(interfaceSource).not.toContain('Research fleet</h2>')
    expect(interfaceSource).not.toContain('<OrchestratorPanel')
    expect(interfaceSource).not.toContain('className="agent-objective"')
    expect(interfaceSource).not.toContain('independent research {props.snapshot.agentCount === 1')
    expect(interfaceSource).toContain('snapshot.orchestratorReasoning')
    expect(interfaceSource).toContain("snapshot.agents.filter((agent) => agent.status !== 'planned')")
    expect(interfaceSource).toContain("answerStarted && !wasAnswerStarted.current")
    expect(interfaceSource).toContain('const [open, setOpen] = useState(false)')
    expect(interfaceSource).toContain("startResearch(event, 'follow-up')")
    expect(interfaceSource).toContain('conversationContext(priorTurns)')
    expect(interfaceSource).toContain('history.map((turn) =>')
    expect(interfaceSource).toContain('Ask a follow-up question')
    expect(interfaceSource).toContain('aria-controls="live-fleet-activity"')
    expect(interfaceSource).toContain("aria-label={open ? 'Hide fleet activity' : 'Show fleet activity'}")
    expect(interfaceSource).toContain("latestTool ? `${latestTool.tool === 'search' ? 'Search' : 'Fetch'}")
    expect(interfaceSource).not.toContain('className="orchestrator-chat"')
    expect(interfaceSource).not.toContain('className="main-agent-stream"')
    expect(interfaceSource).toContain('<AgentTimeline agent={props.agent} compact />')
    expect(interfaceSource).toContain('<AgentTimeline agent={agent} />')
    expect(interfaceSource).not.toContain('Chronological trace')
    expect(interfaceSource).toContain('<Markdown remarkPlugins={[remarkGfm]}>{agent.finding}</Markdown>')
    expect(interfaceSource).toContain('className="bot-sailor-hat"')
    expect(interfaceSource).toContain("if (event.deltaY < 0) onBreakAutoScroll()")
    expect(interfaceSource).toContain('tabIndex={0}')
    expect(interfaceSource).toContain("className={`fleet-dialog ${props.selectedAgent ? 'agent-view' : 'fleet-view'}`}")
    expect(interfaceSource).toContain('Back to fleet')
    expect(interfaceSource).toContain('setSelectedAgentId(null)')
    expect(interfaceStyles).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(interfaceStyles).not.toContain('grid-template-columns: minmax(0, 2fr) minmax(320px, 1fr)')
  })

  it('makes the research ocean a functional view of live fleet state', () => {
    expect(interfaceSource).toContain('What should the fleet investigate?')
    expect(interfaceSource).toContain('Send parallel researchers across the problem, then bring the evidence back into one answer.')
    expect(interfaceSource).toContain('className={`ocean-morph-layer')
    expect(interfaceSource).toContain('snapshot={activeSnapshot ?? undefined}')
    expect(interfaceSource).toContain('oceanTargetRef={oceanTargetRef}')
    expect(interfaceSource.match(/<ResearchOcean/g)).toHaveLength(1)
    expect(interfaceSource).not.toContain('layoutId="research-ocean-shell"')
    expect(interfaceSource).not.toContain('minimumLaunchDuration')
    expect(interfaceSource).toContain('setLaunchSnapshot(nextSnapshot)')
    expect(interfaceSource).toContain('transitionToRun(nextSnapshot)')
    expect(oceanSource).toContain('Math.min(snapshot.agentCount, MAX_VISIBLE_BOATS)')
    expect(oceanSource).toContain("agent.activity.toLowerCase().includes('retry')")
    expect(oceanSource).toContain('onOpenAgent.current?.(agentId)')
    expect(oceanSource).toContain('oceanSources(snapshot.agents)')
    expect(oceanSource).toContain('className="ocean-source-disclosure"')
    expect(oceanSource).toContain('target="_blank"')
    expect(oceanSource).toContain('new THREE.WebGLRenderer')
    expect(oceanSource).toContain('new THREE.QuadraticBezierCurve3')
    expect(oceanSource).toContain('new THREE.Raycaster')
    expect(oceanSource).toContain('new THREE.InstancedMesh')
    expect(oceanSource).toContain('hit?.instanceId')
    expect(oceanSource).toContain('FLEET_REVEAL_DELAY_SECONDS')
    expect(oceanSource).toContain('smootherStep(launchTime)')
    expect(oceanSource).toContain("liveState.current.phase === 'morphing'")
    expect(oceanSource).toContain('const heroRetire =')
    expect(oceanSource).toContain('const harborReveal =')
    expect(oceanSource).toContain('(morph - .68) / .32')
    expect(oceanSource).toContain('createBillowedSail')
    expect(oceanSource).not.toContain('movePreviewBoat')
    expect(oceanSource).toContain('new EffectComposer(renderer)')
    expect(oceanSource).toContain('new UnrealBloomPass')
    expect(oceanSource).toContain('float waveHeight(vec2 p)')
    expect(oceanSource).toContain('float fresnel =')
    expect(oceanSource).toContain('createSeaSparkles')
    expect(oceanSource).toContain('createMist')
    expect(oceanSource).toContain('createDestinationPin')
    expect(oceanSource).toContain('createHarborDock')
    expect(oceanSource).toContain('setDestinationPinColor')
    expect(interfaceStyles).toContain('.ocean-canvas')
    expect(interfaceStyles).toContain('.welcome-transition.launch-exit')
    expect(interfaceStyles).toContain('.welcome-transition.launch-exit .welcome-stage')
    expect(interfaceStyles).toContain('animation: launch-search-away .7s')
    expect(interfaceStyles).toContain('animation: ocean-cave-in 1.8s')
    expect(interfaceStyles).not.toContain('.ocean-transition-compact.complete')
    expect(interfaceSource).toContain('window.setTimeout(resolve, 1900)')
    expect(interfaceStyles).toContain('@keyframes ocean-cave-in')
    expect(interfaceStyles).toContain('.ocean-atmosphere')
    expect(interfaceStyles).toContain('.ocean-agent-target.retrying')
    expect(interfaceStyles).toMatch(/\.intro p \{[^}]*white-space: nowrap/)
    expect(interfaceStyles).toMatch(/@media \(max-width: 720px\)[\s\S]*\.intro p \{[^}]*white-space: normal/)
  })
})
